#!/usr/bin/env bash
#gitrepoupdate

# Check if both directories present
if [ -d GliderWinchItems ]; then
	echo "GliderWinchItems directory present"
	if [ -d GliderWinchCommons ]; then
    	# Update both
		echo "GliderWinch directory present"
		cd GliderWinchItems/docs-common/scripts/gitpull
		./gitpullcommons gitpullcommons.txt
		./gitpullitems gitpullitems.txt
	else
		echo "GliderWinchCommons directory not found"
		exit
	fi
else
	echo GliderWinchItems directory not found
	exit
fi
