#!/bin/bash -e
# compileupdate_GliderWinchItems
# Lastest compile
# Essentials, (for now)
# 07/07/2024
# 08/03/2024 Add crc-srec (in ./cc script sequence)
#
echo "====================================================="
echo "=============== CAN1loader/ldrfixedL431 ============="
echo " Compile not done here: ldrfixedL431 compiles for each CAN id "
#cd ~/GliderWinchItems/CANloader1/ldrfixedL431
#./mm
echo "=============== CAN1loader/PC/crc-srec =============="
echo "gcc -Wall crc-srec.c crc-32_nib.c -o crc-srec"
cd ~/GliderWinchItems/CANloader1/PC/crc-srec
gcc -Wall crc-srec.c crc-32_nib.c -o crc-srec
echo "====================================================="
echo

echo "====================================================="
echo "=============== can-server =========================="
cd ~/GliderWinchItems/can-server
make
echo "====================================================="
echo

echo "========== hub-server-bridge sand1 =================="
cd ~/GliderWinchItems/hub-server-bridge/sandboxes/sand1/trunk
./m sand1
echo "====================================================="
echo


