#!/bin/bash 
# gitpushupdate
# Essentials, (for now)
# 07/07/2024
#
git config --local status.showUntrackedFiles no
./gitpushheader ~/GliderWinchCommons/embed

./gitpushheader ~/GliderWinchItems/BMS

./gitpushheader ~/GliderWinchItems/can-server

./gitpushheader ~/GliderWinchItems/CANloader1

./gitpushheader ~/GliderWinchItems/docs-common

./gitpushheader ~/GliderWinchItems/drum

./gitpushheader ~/GliderWinchItems/hub-server-bridge
git config --local status.showUntrackedFiles yes


