#!/bin/bash 
# gitpushupdate
# Essentials, (for now)
# 07/07/2024
#

./gitpushheader ~/GliderWinchCommons/embed

./gitpushheader ~/GliderWinchItems/BMS

./gitpushheader ~/GliderWinchItems/can-server

./gitpushheader ~/GliderWinchItems/CANloader1

./gitpushheader ~/GliderWinchItems/docs-common

./gitpushheader ~/GliderWinchItems/drum

./gitpushheader ~/GliderWinchItems/hub-server-bridge



